package com.example.auth.domain.audit;

public enum AuditEventType {
    USER_REGISTERED,
    LOGIN_SUCCEEDED,
    LOGIN_FAILED_BAD_CREDENTIALS,
    LOGIN_FAILED_USER_LOCKED,
    LOGIN_FAILED_RATE_LIMITED,
    MFA_REQUIRED,
    MFA_VERIFIED,
    MFA_FAILED,
    MFA_ENABLED,
    MFA_DISABLED,
    REFRESH_ROTATED,
    REFRESH_REUSE_DETECTED,
    SESSION_REVOKED_BY_USER,
    SESSION_REVOKED_BY_REUSE,
    ROLE_ASSIGNED,
    ROLE_REVOKED
}
